# Generated by Django 6.0.3 on 2026-03-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pelicula_disponible_alter_pelicula_anio'),
    ]

    operations = [
    ]
