# Generated by Django 6.0.3 on 2026-03-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20260331_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='disponible',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='stock',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
