# Generated by Django 6.0.3 on 2026-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_pelicula_disponible_pelicula_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
