# Generated by Django 6.0.3 on 2026-04-03 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
    ]
