# Generated by Django 6.0.3 on 2026-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='pagado',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10),
        ),
    ]
