# Generated by Django 6.0.3 on 2026-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_alquiler_pagado_alquiler_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
