# Generated by Django 6.0.3 on 2026-04-04 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_metodopago_alquiler_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=90, help_text='Duración de la película en minutos.', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
