# Generated by Django 6.0.3 on 2026-04-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_pelicula_duracion_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
