# Generated by Django 6.0.3 on 2026-04-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_pelicula_director_pelicula_pais_origen'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alquiler',
            constraint=models.UniqueConstraint(fields=('cliente', 'pelicula', 'fecha_alquiler'), name='unique_alquiler_cliente_pelicula_fecha'),
        ),
    ]
